### PR TITLE
Allow optional parameters for new instance creation

### PR DESCRIPTION
**Pull request by megallo**
Changes 9 parameters from being required to being optional during new instance creation. If the parameter does not exist in the run configurations, do not send it at all in the AWS API call. There are no default values sent to AWS.  This change works because AWS will supplement the missing information with the values of the snapshot being cloned into the new instance.

This change does not check or enforce any AWS API restrictions, such as requiring IOPS if the storage type is set, etc.

Optional-ness of parameters taken from [API](http://docs.aws.amazon.com//AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromDBSnapshot.html)

### CODE REVIEW

**Comment by megallo** [comment]
Tested again after merge from master. Still works as expected. :tada:

**Comment by megallo** [comment]
Output when testing with no optional parameters set in input configuration

```
2016-03-29 16:11:37 -0500 INFO rdsecho.properties file not found; reading configuration from VM properties directly
2016-03-29 16:11:43 -0500 INFO [new] Checking to see if current echo-created instance (tagged <snip>) was created less than 24 hours ago. If so this operation will not continue.
2016-03-29 16:11:45 -0500 INFO [new] Last echo-created RDS instance <snip> was created more than 24 hours ago. Proceeding.
2016-03-29 16:11:45 -0500 INFO [new] Locating latest snapshot from <snip>
2016-03-29 16:11:46 -0500 INFO [new] Located snapshot <snip> completed on <snip>
2016-03-29 16:11:46 -0500 INFO [new] Proposed new db instance...
  db snapshot id   : <snip>
  db instance id   : <snip>

2016-03-29 16:11:46 -0500 INFO Proceed to create a new DB instance from this snapshot? Input <snip> to confirm.
```

**Comment by megallo** [comment]
Output when testing without IOPS or storage options set in configuration. This results in a db with the same IOPS/storage as the base snapshot.

```
2016-03-29 16:16:01 -0500 INFO [new] Proposed new db instance...
  db snapshot id   : <snip>
  db instance id   : <snip>
  engine           : MySQL
  license model    : general-public-license
  db instance class: <snip>
  multi az         : false
  port             : <snip>
  option group name: <snip>
  auto minor ver up: true
```

**Comment by rholder** [comment]
This looks great. Let's pull it in and get everything ready for the next release.

**Comment by megallo** [comment]
Cool, I'll push one more commit to update the version.

**Pull request merged**
